### ISSUE TITLE
Email Address

### ISSUE THREAD

**Issue by rchampieux** [OHSULibrary-DataScienceInstitute/Project-Management#1]
Robin asked Shannon to request a distribution list for ODSI, so anyone can email us and all of use will receive messages.

**Comment by rchampieux** [comment]
Additionaly:
- [x] need to add email address to the code of conduct
https://github.com/OHSULibrary-DataScienceInstitute/OHSULibrary-DataScienceInstitute.github.io/blob/master/codeOfConduct.md 
- [x] need to add email to the registration form, #8

**Comment by nicolevasilevsky** [comment]
The email address is:  OHSULibraryDataScienceInstitute@ohsu.edu
